using System;
using System.Collections.Generic;
using System.Diagnostics.Metrics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WorkerOperaCloud.Models
{
    public class Mdl_Rep_Manager
    {
        public DateTime? BUSINESS_DATE { get; set; }
        public string? ROOM_CLASS { get; set; }
        public string? RESORT { get; set; }
        public string? OCC_ROOM { get; set; }
        public string? COMP_ROOM { get; set; }
        public string? HOUSE_USE_ROOM { get; set; }
        public string? DAYUSE_ROOM { get; set; }
        public string? AVAIL_ROOM { get; set; }
        public string? OOO_ROOMS { get; set; }
        public string? OS_ROOMS { get; set; }
        public string? ADR_ROOM_WO_COMP_HOUSE { get; set; }
        public string? AVERAGE_DAILY_REVENUE { get; set; }
        public string? GUEST_IN_HOUSE { get; set; }
        public string? PER_OCCUPANCY { get; set; }
        public string? PER_OCC_WO_COMP_HOUSE { get; set; }
        public string? PER_OCC_WO_COMP_HOUSE_OO { get; set; }
        public string? ARRIVAL_ROOM { get; set; }
        public string? ARRIVAL_PRS { get; set; }
        public string? DEPARTURE_ROOM { get; set; }
        public string? DEPARTURE_PRS { get; set; }
        public string? EXT_STAY_ROOM { get; set; }
        public string? EXT_STAY_PRS { get; set; }
        public string? EARLY_DEP_ROOM { get; set; }
        public string? EARLY_DEP_PRS { get; set; }
        public string? WALKIN_ROOM { get; set; }
        public string? WALKIN_PRS { get; set; }
        public string? NOSHOW_ROOM { get; set; }
        public string? NOSHOW_PRS { get; set; }
        public string? CANCEL_RESERVATION { get; set; }
        public string? CANCEL_ROOMS { get; set; }
        public string? LATE_CANCEL_RESERVATION { get; set; }
        public string? LATE_CANCEL_ROOMS { get; set; }
        public string? RESERVATION { get; set; }
        public string? TURNAWAY { get; set; }
        public string? TOMORROW_ARRIVAL_ROOM { get; set; }
        public string? TOMORROW_ARRIVAL_PRS { get; set; }
        public string? TOMORROW_DEPARTURE_ROOM { get; set; }
        public string? TOMORROW_DEPARTURE_PRS { get; set; }
        public string? FOOD_BEV_REVENUE { get; set; }
        public string? OCC_WEEK { get; set; }
        public string? OCC_MONTH { get; set; }
        public string? OCC_YEAR { get; set; }
        public string? ROOM_REVENUE { get; set; }
        public string? CLEAN_ROOM { get; set; }
        public string? INSPECTED_ROOM { get; set; }
        public string? PAYMENT { get; set; }
        public string? GROUP_REVENUE { get; set; }
        public string? GROUP_ROOM { get; set; }
        public string? VIP_GUEST { get; set; }
        public string? NO_OF_GROUP { get; set; }
        public string? GROUP_PRS { get; set; }
        public string? GROUP_ROOM_REV { get; set; }
        public string? ADULTS_IN_HOUSE { get; set; }
        public string? CHILDREN_IN_HOUSE { get; set; }
        public string? OTHER_REVENUE { get; set; }
        public string? TOTAL_REVENUE { get; set; }
        public string? PHYSICAL_ROOM { get; set; }
        public string? OCC_TOMMORROW { get; set; }
        public string? SINGLE_OCC_ROOM { get; set; }
        public string? MULTI_OCC_ROOM { get; set; }
        public string? ROOM_TAX { get; set; }
        public string? FOOD_BEV_TAX { get; set; }
        public string? OTHER_TAX { get; set; }
        public string? TOTAL_TAX { get; set; }
        public string? GROUP_TAX { get; set; }
        public string? GROUP_ROOM_TAX { get; set; }
        public string? FIT_GUESTS_TODAY { get; set; }
        public string? AGENT_ROOMS_TODAY { get; set; }
        public string? COMPANY_ROOMS_TODAY { get; set; }
        public string? SOURCE_ROOMS_TODAY { get; set; }
        public string? DEF_ARRIVALS_TODAY { get; set; }
        public string? TNT_ARRIVALS_TODAY { get; set; }
        public string? DIRTY_ROOMS_TODAY { get; set; }
        public string? BIRTHDAYS { get; set; }
        public string? DBLS_AS_SGLS_TODAY { get; set; }
        public string? CANCELLATIONS_MADE_TODAY { get; set; }
        public string? ROOM_NIGHTS_RESERVED_TODAY { get; set; }
        public string? FIT_REVENUE_TODAY { get; set; }
        public string? MEMBER_TOTAL_TAX { get; set; }
        public string? MEM_REVENUE_TODAY { get; set; }
        public string? FIT_DEP_TODAY { get; set; }
        public string? FIT_DEP_PRS_TODAY { get; set; }
        public string? MEM_DEP_PRS_TODAY { get; set; }
        public string? FIT_MEM_DEP_PRS { get; set; }
        public string? MEM_INHOUSE_PRS_TODAY { get; set; }
        public string? BEDS_AVL_TODAY { get; set; }
        public string? CRIBS_TODAY { get; set; }
        public string? AVERAGE_AGE_TODAY { get; set; }
        public string? ROLLAWAYS_TODAY { get; set; }
        public string? ADULTS_FREE_TODAY { get; set; }
        public string? CHILDREN_FREE_TODAY { get; set; }
        public string? RACK_RATE_OCC { get; set; }
        public string? YIELD_ALL_ROOMS { get; set; }
        public string? YIELD_OCC_ROOMS { get; set; }
        public string? RACK_RATE_ALL { get; set; }
        public string? FIT_ROOMS_TODAY { get; set; }
        public string? GROUP_ROOMS_TODAY { get; set; }
        public string? FIT_MEM_DEP_ROOMS { get; set; }
        public string? MEM_DEP_ROOMS_TODAY { get; set; }
        public string? FIT_ROOM_REVENUE { get; set; }
        public string? INHOUSE_MAX_OCCUPANCY { get; set; }
        public string? EXT_NOSHOW_PRS { get; set; }
        public string? EXT_NOSHOW_ROOM { get; set; }
        public string? EXT_NOSHOW_RES { get; set; }
        public string? CHILDREN1 { get; set; }
        public string? CHILDREN2 { get; set; }
        public string? CHILDREN3 { get; set; }
        public string? CHILDREN4 { get; set; }
        public string? CHILDREN5 { get; set; }
        public string? OCC_NEXT_31_DAYS { get; set; }
        public string? OCC_NEXT_365_DAYS { get; set; }
        public string? OCC_REST_OF_MONTH { get; set; }
        public string? OCC_REST_OF_YEAR { get; set; }
        public string? COMPANY_ROOM_REVENUE { get; set; }
        public string? COMPANY_ROOM_TAX { get; set; }
        public string? COMPANY_TOTAL_REVENUE { get; set; }
        public string? COMPANY_TOTAL_TAX { get; set; }
        public string? AGENT_ROOM_REVENUE { get; set; }
        public string? AGENT_ROOM_TAX { get; set; }
        public string? AGENT_TOTAL_REVENUE { get; set; }
        public string? AGENT_TOTAL_TAX { get; set; }
        public string? REPEAT_ROOMS { get; set; }
        public string? REPEAT_PERSONS { get; set; }
        public string? REPEAT_ROOM_REVENUE { get; set; }
        public string? REPEAT_ROOM_TAX { get; set; }
        public string? REPEAT_TOTAL_REVENUE { get; set; }
        public string? REPEAT_TOTAL_TAX { get; set; }
        public string? NOSHOW_RESERVATIONS { get; set; }
        public string? DAY_USE_RESERVATIONS { get; set; }
        public string? ARRIVAL_RESERVATIONS { get; set; }
        public string? ROOMS_CANCELLED_TODAY { get; set; }
        public string? OWNER_ROOMS { get; set; }
        public string? OWNER_ROOM_REVENUE { get; set; }
        public string? OWNER_OTHER_REVENUE { get; set; }
        public string? OWNER_FOOD_BEV_REVENUE { get; set; }
        public string? FF_ROOMS { get; set; }
        public string? FF_ROOM_REVENUE { get; set; }
        public string? FF_OTHER_REVENUE { get; set; }
        public string? FF_FOOD_BEV_REVENUE { get; set; }
        public string? CENTRAL_CURRENCY_CODE { get; set; }
        public string? CENTRAL_EXCHANGE_RATE { get; set; }
        public string? PHYSICAL_BEDS { get; set; }
        public string? OCC_BEDS { get; set; }
        public string? COMP_BEDS { get; set; }
        public string? HOUSE_USE_BEDS { get; set; }
        public string? OOO_BEDS { get; set; }
        public string? OS_BEDS { get; set; }
        public string? COMP_ADULTS { get; set; }
        public string? COMP_CHILDREN { get; set; }
        public string? HOUSE_USE_ADULTS { get; set; }
        public string? HOUSE_USE_CHILDREN { get; set; }
        public string? FIT_MEM_ROOMS { get; set; }
        public string? FIT_MEM_ROOM_REVENUE { get; set; }
        public string? FIT_MEM_ROOM_REVENUE_TAX { get; set; }
        public string? FIT_MEM_TOTAL_REVENUE { get; set; }
        public string? FIT_MEM_TOTAL_REVENUE_TAX { get; set; }
        public string? FIT_MEM_LOS_NIGHTS { get; set; }
        public string? FIT_MEM_LOS_RESV { get; set; }
        public string? BLK_MEM_ROOMS { get; set; }
        public string? BLK_MEM_ROOM_REVENUE { get; set; }
        public string? BLK_MEM_ROOM_REVENUE_TAX { get; set; }
        public string? BLK_MEM_TOTAL_REVENUE { get; set; }
        public string? BLK_MEM_TOTAL_REVENUE_TAX { get; set; }
        public string? BLK_MEM_LOS_NIGHTS { get; set; }
        public string? BLK_MEM_LOS_RESV { get; set; }
        public string? ADV_FOOD_REVENUE { get; set; }
        public string? ADV_NON_REVENUE { get; set; }
        public string? ADV_OTHER_REVENUE { get; set; }
        public string? ADV_ROOM_REVENUE { get; set; }
        public string? ADV_TOTAL_FOOD_TAX { get; set; }
        public string? ADV_TOTAL_NON_REVENUE_TAX { get; set; }
        public string? ADV_TOTAL_OTHER_TAX { get; set; }
        public string? ADV_TOTAL_REVENUE { get; set; }
        public string? ADV_TOTAL_ROOM_TAX { get; set; }
        public string? ADV_TOTAL_TAX { get; set; }
        public string? FF_RENT_FOOD_BEV_REV { get; set; }
        public string? FF_RENT_OTHER_REV { get; set; }
        public string? FF_RENT_ROOMS { get; set; }
        public string? FF_RENT_ROOM_REV { get; set; }
        public string? OWNER_RENT_FOOD_BEV_REV { get; set; }
        public string? OWNER_RENT_OTHER_REV { get; set; }
        public string? OWNER_RENT_ROOMS { get; set; }
        public string? OWNER_RENT_ROOMS_OOO { get; set; }
        public string? OWNER_RENT_ROOM_REV { get; set; }
        public string? OWNER_ROOMS_OOO { get; set; }
        public string? FLGD_ROOM_REVENUE { get; set; }
        public string? FLGD_FOOD_REVENUE { get; set; }
        public string? FLGD_NON_REVENUE { get; set; }
        public string? FLGD_OTHER_REVENUE { get; set; }
        public string? FLGD_TOTAL_ROOM_TAX { get; set; }
        public string? FLGD_TOTAL_FOOD_TAX { get; set; }
        public string? FLGD_TOTAL_NON_REVENUE_TAX { get; set; }
        public string? FLGD_TOTAL_OTHER_TAX { get; set; }
        public string? FLGD_TOTAL_REVENUE { get; set; }
        public string? FLGD_TOTAL_TAX { get; set; }
        public string? FLGD_PAYMENT { get; set; }
        public string? DAYUSE_REST_OF_YEAR { get; set; }
        public string? DAYUSE_REST_OF_MONTH { get; set; }
        public string? DAYUSE_NEXT_365_DAYS { get; set; }
        public string? DAYUSE_NEXT_31_DAYS { get; set; }
        public string? DAYUSE_YEAR { get; set; }
        public string? DAYUSE_MONTH { get; set; }
        public string? DAYUSE_WEEK { get; set; }
        public string? OWNER_ROOMS_IN_HOTEL { get; set; }
        public string? EXT_NOSHOW_CRS_RES { get; set; }
        public string? DAYUSE_TOMORROW { get; set; }
        public string? COMP_REST_OF_YEAR { get; set; }
        public string? COMP_REST_OF_MONTH { get; set; }
        public string? COMP_NEXT_365_DAYS { get; set; }
        public string? COMP_NEXT_31_DAYS { get; set; }
        public string? COMP_WEEK { get; set; }
        public string? COMP_TOMORROW { get; set; }
        public string? HOUSE_USE_REST_OF_YEAR { get; set; }
        public string? HOUSE_USE_REST_OF_MONTH { get; set; }
        public string? HOUSE_USE_NEXT_365_DAYS { get; set; }
        public string? HOUSE_USE_NEXT_31_DAYS { get; set; }
        public string? HOUSE_USE_WEEK { get; set; }
        public string? HOUSE_USE_TOMORROW { get; set; }
        public string? OOO_ROOMS_REST_OF_YEAR { get; set; }
        public string? OOO_ROOMS_REST_OF_MONTH { get; set; }
        public string? OOO_ROOMS_NEXT_365_DAYS { get; set; }
        public string? OOO_ROOMS_NEXT_31_DAYS { get; set; }
        public string? OOO_ROOMS_WEEK { get; set; }
        public string? OOO_ROOMS_TOMORROW { get; set; }
        public string? OS_ROOMS_REST_OF_YEAR { get; set; }
        public string? OS_ROOMS_REST_OF_MONTH { get; set; }
        public string? OS_ROOMS_NEXT_365_DAYS { get; set; }
        public string? OS_ROOMS_NEXT_31_DAYS { get; set; }
        public string? OS_ROOMS_WEEK { get; set; }
        public string? OS_ROOMS_TOMORROW { get; set; }
        public string? DAYUSE_ADULTS { get; set; }
        public string? DAYUSE_CHILDREN { get; set; }
        public string? ES_OCC_ROOMS { get; set; }
        public string? ES_COMP_ROOMS { get; set; }
        public string? ES_HOUSE_USE_ROOMS { get; set; }
        public string? ES_TOTAL_REVENUE { get; set; }
        public string? ES_ROOM_REVENUE { get; set; }
        public string? ES_FOOD_REVENUE { get; set; }
        public string? ES_OTHER_REVENUE { get; set; }
        public string? ES_NON_REVENUE { get; set; }
        public string? ES_TOTAL_TAX { get; set; }
        public string? ES_ROOM_TAX { get; set; }
        public string? ES_FOOD_TAX { get; set; }
        public string? ES_OTHER_TAX { get; set; }
        public string? ES_NON_REVENUE_TAX { get; set; }
        public string? ES_ADV_TOTAL_REVENUE { get; set; }
        public string? ES_ADV_ROOM_REVENUE { get; set; }
        public string? ES_ADV_FOOD_REVENUE { get; set; }
        public string? ES_ADV_OTHER_REVENUE { get; set; }
        public string? ES_ADV_NON_REVENUE { get; set; }
        public string? ES_ADV_TOTAL_TAX { get; set; }
        public string? ES_ADV_ROOM_TAX { get; set; }
        public string? ES_ADV_FOOD_TAX { get; set; }
        public string? ES_ADV_OTHER_TAX { get; set; }
        public string? ES_ADV_NON_REVENUE_TAX { get; set; }
        public DateTime? RNA_INSERTDATE { get; set; } = null;
        public DateTime? RNA_UPDATEDATE { get; set; } = null;
        public string? DELETED_FLAG { get; set; } = "";

    }
}
