using System;
using System.Collections.Generic;
using System.DirectoryServices.ActiveDirectory;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using System.Xml.Linq;
namespace WorkerOperaCloud.Models
{
    public class Mdl_Name
    {
        public string? NAME_ID {get;set;} 
        public string? NAME_CODE {get;set;}   
        public string? INSERT_USER {get;set;} 
        public DateTime? INSERT_DATE {get;set;} 
        public string? UPDATE_USER {get;set;} 
        public DateTime? UPDATE_DATE {get;set;} 
        public string? PRIMARY_NAME_ID {get;set;} 
        public string? REPEAT_GUEST_ID {get;set;} 
        public string? MAIL_LIST {get;set;} 
        public string? MAIL_TYPE {get;set;}   
        public string? FOLLOW_ON {get;set;} 
        public string? BUSINESS_TITLE {get;set;}  
        public DateTime? INACTIVE_DATE {get;set;} 
        public DateTime? ARC_UPDATE_DATE {get;set;} 
        public DateTime? UPDATE_FAX_DATE {get;set;} 
        public DateTime? BIRTH_DATE {get;set;}  
        public string? COLLECTION_USER_ID {get;set;} 
        public string? COMPANY {get;set;} 
        public string? SOUND_EX_COMPANY {get;set;} 
        public string? LEGAL_COMPANY {get;set;}   
        public string? FIRST {get;set;} 
        public string? MIDDLE {get;set;}  
        public string? LAST {get;set;} 
        public string? NICKNAME {get;set;}    
        public string? TITLE {get;set;} 
        public string? SOUND_EX_LAST {get;set;}   
        public string? EXTERNAL_REFERENCE_REQU {get;set;} 
        public string? VIP_STATUS {get;set;}  
        public string? VIP_AUTHORIZATION {get;set;} 
        public string? BILLING_PROFILE_CODE {get;set;}    
        public string? RATE_STRUCTURE {get;set;} 
        public string? NAME_COMMENT {get;set;}    
        public string? TOUR_OPERATOR_TYPE {get;set;} 
        public string? REGION {get;set;}  
        public string? TYPE_OF_1099 {get;set;} 
        public string? TAX1_NO {get;set;} 
        public string? COMPANY_NAME_ID {get;set;} 
        public string? EXTERNAL_REFERENCE_REQUIRED {get;set;} 
        public string? VENDOR_ID {get;set;} 
        public string? VENDOR_SITE_ID {get;set;}  
        public string? ARC_OFFICE_TYPE {get;set;} 
        public string? TAX2_NO {get;set;} 
        public string? ARC_MAIL_FLAG {get;set;} 
        public string? NAME2 {get;set;}   
        public string? NAME3 {get;set;} 
        public string? SALESREP {get;set;}    
        public string? TRACECODE {get;set;} 
        public string? GEOGRAPHIC_REGION {get;set;}   
        public string? GUEST_CLASSIFICATION {get;set;} 
        public string? PRIMARY_ADDRESS_ID {get;set;}  
        public string? PRIMARY_PHONE_ID {get;set;} 
        public string? TAX_EXEMPT_STATUS {get;set;}   
        public string? GDS_NAME {get;set;} 
        public string? GDS_TRANSACTION_NO {get;set;}  
        public string? NATIONALITY {get;set;} 
        public string? LANGUAGE {get;set;}    
        public string? SALUTATION {get;set;} 
        public string? PASSPORT {get;set;}    
        public string? HISTORY_YN {get;set;} 
        public string? RESV_CONTACT {get;set;}    
        public string? CONTRACT_NO {get;set;} 
        public DateTime? CONTRACT_RECV_DATE {get;set;}  
        public string? ACCT_CONTACT {get;set;} 
        public string? PRIORITY {get;set;}    
        public string? INDUSTRY_CODE {get;set;} 
        public string? ROOMS_POTENTIAL {get;set;} 
        public string? COMPETITION_CODE {get;set;} 
        public string? SCOPE {get;set;}   
        public string? SCOPE_CITY {get;set;} 
        public string? TERRITORY {get;set;}   
        public string? ACTIONCODE {get;set;} 
        public string? ACTIVE_YN {get;set;}   
        public string? MASTER_ACCOUNT_YN {get;set;} 
        public string? NAME_TYPE {get;set;}   
        public string? SNAME {get;set;} 
        public string? NAME_TAX_TYPE {get;set;}   
        public string? SFIRST {get;set;} 
        public string? AR_NO {get;set;}   
        public string? AVAILABILITY_OVERRIDE {get;set;} 
        public string? BILLING_CODE {get;set;}    
        public string? CASH_BL_IND {get;set;} 
        public string? BL_MSG {get;set;}  
        public string? CURRENCY_CODE {get;set;} 
        public string? COMMISSION_CODE {get;set;} 
        public string? HOLD_CODE {get;set;}
        public string? INTEREST { get; set; }
        public string? SUMM_REF_CC {get;set;} 
        public string? IATA_COMP_TYPE {get;set;}  
        public string? SREP_CODE {get;set;} 
        public string? ACCOUNTSOURCE {get;set;}   
        public string? MARKETS {get;set;} 
        public string? PRODUCT_INTEREST {get;set;}    
        public string? KEYWORD {get;set;} 
        public string? LETTER_GREETING {get;set;} 
        public string? INFLUENCE {get;set;} 
        public string? DEPT_ID {get;set;} 
        public string? DEPARTMENT {get;set;} 
        public string? CONTACT_YN {get;set;}  
        public string? ACCOUNT_TYPE {get;set;} 
        public string? DOWNLOAD_RESORT {get;set;} 
        public string? DOWNLOAD_SREP {get;set;} 
        public DateTime? DOWNLOAD_DATE {get;set;}   
        public DateTime? UPLOAD_DATE {get;set;} 
        public string? LAPTOP_CHANGE {get;set;}   
        public string? CRS_NAMEID {get;set;} 
        public string? COMM_PAY_CENTRAL {get;set;}    
        public string? CC_PROFILE_YN {get;set;} 
        public string? GENDER {get;set;}  
        public string? BIRTH_PLACE {get;set;} 
        public string? BIRTH_COUNTRY {get;set;}   
        public string? PROFESSION {get;set;} 
        public string? ID_TYPE {get;set;} 
        public string? ID_NUMBER {get;set;} 
        public DateTime? ID_DATE {get;set;} 
        public string? ID_PLACE {get;set;} 
        public string? ID_COUNTRY {get;set;}  
        public string? UDFC01 {get;set;} 
        public string? UDFC02 {get;set;}  
        public string? UDFC03 {get;set;} 
        public string? UDFC04 {get;set;}  
        public string? UDFC05 {get;set;} 
        public string? UDFC06 {get;set;}  
        public string? UDFC07 {get;set;} 
        public string? UDFC08 {get;set;}  
        public string? UDFC09 {get;set;} 
        public string? UDFC10 {get;set;}  
        public string? UDFC11 {get;set;} 
        public string? UDFC12 {get;set;}  
        public string? UDFC13 {get;set;} 
        public string? UDFC14 {get;set;}  
        public string? UDFC15 {get;set;} 
        public string? UDFC16 {get;set;}  
        public string? UDFC17 {get;set;} 
        public string? UDFC18 {get;set;}  
        public string? UDFC19 {get;set;} 
        public string? UDFC20 {get;set;}  
        public string? UDFC21 {get;set;} 
        public string? UDFC22 {get;set;}  
        public string? UDFC23 {get;set;} 
        public string? UDFC24 {get;set;}  
        public string? UDFC25 {get;set;} 
        public string? UDFC26 {get;set;}  
        public string? UDFC27 {get;set;} 
        public string? UDFC28 {get;set;}  
        public string? UDFC29 {get;set;} 
        public string? UDFC30 {get;set;}  
        public string? UDFC31 {get;set;} 
        public string? UDFC32 {get;set;}  
        public string? UDFC33 {get;set;} 
        public string? UDFC34 {get;set;}  
        public string? UDFC35 {get;set;} 
        public string? UDFC36 {get;set;}  
        public string? UDFC37 {get;set;} 
        public string? UDFC38 {get;set;}  
        public string? UDFC39 {get;set;} 
        public string? UDFC40 {get;set;}  
        public string? UDFN01 {get;set;} 
        public string? UDFN02 {get;set;}  
        public string? UDFN03 {get;set;} 
        public string? UDFN04 {get;set;}  
        public string? UDFN05 {get;set;} 
        public string? UDFN06 {get;set;}  
        public string? UDFN07 {get;set;} 
        public string? UDFN08 {get;set;}  
        public string? UDFN09 {get;set;} 
        public string? UDFN10 {get;set;}  
        public string? UDFN11 {get;set;} 
        public string? UDFN12 {get;set;}  
        public string? UDFN13 {get;set;} 
        public string? UDFN14 {get;set;}  
        public string? UDFN15 {get;set;} 
        public string? UDFN16 {get;set;}  
        public string? UDFN17 {get;set;} 
        public string? UDFN18 {get;set;}  
        public string? UDFN19 {get;set;} 
        public string? UDFN20 {get;set;}  
        public string? UDFN21 {get;set;} 
        public string? UDFN22 {get;set;}  
        public string? UDFN23 {get;set;} 
        public string? UDFN24 {get;set;}  
        public string? UDFN25 {get;set;} 
        public string? UDFN26 {get;set;}  
        public string? UDFN27 {get;set;} 
        public string? UDFN28 {get;set;}  
        public string? UDFN29 {get;set;} 
        public string? UDFN30 {get;set;}  
        public string? UDFN31 {get;set;} 
        public string? UDFN32 {get;set;}  
        public string? UDFN33 {get;set;} 
        public string? UDFN34 {get;set;}  
        public string? UDFN35 {get;set;} 
        public string? UDFN36 {get;set;}  
        public string? UDFN37 {get;set;} 
        public string? UDFN38 {get;set;}  
        public string? UDFN39 {get;set;} 
        public string? UDFN40 {get;set;}  
        public DateTime? UDFD01 {get;set;} 
        public DateTime? UDFD02 {get;set;}  
        public DateTime? UDFD03 {get;set;} 
        public DateTime? UDFD04 {get;set;}  
        public DateTime? UDFD05 {get;set;} 
        public DateTime? UDFD06 {get;set;}  
        public DateTime? UDFD07 {get;set;} 
        public DateTime? UDFD08 {get;set;}  
        public DateTime? UDFD09 {get;set;} 
        public DateTime? UDFD10 {get;set;}  
        public DateTime? UDFD11 {get;set;} 
        public DateTime? UDFD12 {get;set;}  
        public DateTime? UDFD13 {get;set;} 
        public DateTime? UDFD14 {get;set;}  
        public DateTime? UDFD15 {get;set;} 
        public DateTime? UDFD16 {get;set;}  
        public DateTime? UDFD17 {get;set;} 
        public DateTime? UDFD18 {get;set;}  
        public DateTime? UDFD19 {get;set;} 
        public DateTime? UDFD20 {get;set;}  
        public string? PAYMENT_DUE_DAYS {get;set;} 
        public string? SUFFIX {get;set;}  
        public string? EXTERNAL_ID {get;set;} 
        public string? GUEST_PRIV_YN {get;set;}   
        public string? EMAIL_YN {get;set;} 
        public string? MAIL_YN {get;set;} 
        public string? INDEX_NAME {get;set;} 
        public string? XLAST_NAME {get;set;}  
        public string? XFIRST_NAME {get;set;} 
        public string? XCOMPANY_NAME {get;set;}   
        public string? XTITLE {get;set;} 
        public string? XSALUTATION {get;set;} 
        public string? SXNAME {get;set;} 
        public string? SXFIRST_NAME {get;set;}
        public string? LAST_UPDATED_RESORT {get;set;} 
        public string? ENVELOPE_GREETING {get;set;}   
        public string? XENVELOPE_GREETING {get;set;} 
        public string? DIRECT_BILL_BATCH_TYPE {get;set;}  
        public string? RESORT_REGISTERED {get;set;} 
        public string? TAX_OFFICE {get;set;}  
        public string? TAX_TYPE {get;set;} 
        public string? TAX_CATEGORY {get;set;}    
        public string? PREFERRED_ROOM_NO {get;set;} 
        public string? PHONE_YN {get;set;}    
        public string? SMS_YN {get;set;} 
        public string? PROTECTED {get;set;}   
        public string? XLANGUAGE {get;set;} 
        public string? MARKET_RESEARCH_YN {get;set;}  
        public string? THIRD_PARTY_YN {get;set;} 
        public string? AUTOENROLL_MEMBER_YN {get;set;}    
        public string? CHAIN_CODE {get;set;} 
        public string? CREDIT_RATING {get;set;}   
        public string? TITLE_SUFFIX {get;set;} 
        public string? COMPANY_GROUP_ID {get;set;}    
        public string? INACTIVE_REASON {get;set;} 
        public string? IATA_CONSORTIA {get;set;}  
        public string? INCLUDE_IN_1099_YN {get;set;} 
        public string? PSUEDO_PROFILE_YN {get;set;}   
        public string? PROFILE_PRIVACY_FLG {get;set;} 
        public string? REPLACE_ADDRESS {get;set;} 
        public string? ALIEN_REGISTRATION_NO {get;set;} 
        public string? IMMIGRATION_STATUS {get;set;}  
        public string? VISA_VALIDITY_TYPE {get;set;} 
        public string? ID_DOCUMENT_ATTACH_ID {get;set;}   
        public string? SUPER_SEARCH_INDEX_TEXT {get;set;} 
        public string? BIRTH_DATE_STR {get;set;}  
        public string? ORIG_NAME_ID {get;set;} 
        public string? D_OPT_IN_MAIL_LIST_FLG {get;set;}  
        public string? D_OPT_IN_MARKET_RESEARCH_FLG {get;set;} 
        public string? D_OPT_IN_THIRD_PARTY_FLG {get;set;}    
        public string? D_OPT_IN_AUTOENROLL_MEMBER_FLG {get;set;} 
        public string? D_OPT_IN_EMAIL_FLG {get;set;}  
        public string? D_OPT_IN_PHONE_FLG {get;set;} 
        public string? D_OPT_IN_SMS_FLG {get;set;}    
        public string? D_OPT_IN_GUEST_PRIV_FLG {get;set;} 
        public string? AR_CREDIT_LIMIT_YN {get;set;}  
        public string? PROFILE_CREDIT_LIMIT {get;set;} 
        public string? XMIDDLE_NAME {get;set;}    
        public string? E_INVOICE_LIABLE_YN {get;set;} 
        public DateTime? E_INV_LIABLE_LAST_UPDATED {get;set;}   
        public string? INTERNAL_BILL_YN {get;set;} 
        public string? ANONYMIZATION_STATUS {get;set;}    
        public DateTime? ANONYMIZATION_DATE {get;set;}
        public DateTime? RNA_INSERTDATE { get; set; } = null;
        public DateTime? RNA_UPDATEDATE { get; set; } = null;
        public string? DELETED_FLAG { get; set; } = "";
    }
}

