using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WorkerOperaCloud.Models
{
    public class Mdl_Rate_Header
    {
        public string? RESORT { get; set; }
        public string? RATE_CODE { get; set; }
        public string? RATE_CLASS { get; set; }
        public string? RATE_CATEGORY { get; set; }
        public string? LOS_UNIT { get; set; }
        public string? SELL_SEQUENCE { get; set; }
        public string? PACKAGE_YN { get; set; }
        public string? DESCRIPTION { get; set; }
        public string? FLAT_OR_PERCENTAGE { get; set; }
        public string? OPERATOR_TYPE { get; set; }
        public string? BASE_RATE_CODE { get; set; }
        public string? ORDER_BY { get; set; }
        public string? ALTERNATE_RATE_CODE { get; set; }
        public string? COMMISSION_CODE { get; set; }
        public string? COMMISSION_YN { get; set; }
        public string? LABEL { get; set; }
        public string? FOLIO_TEXT { get; set; }
        public string? RATE_INCLUDES_TAX_YN { get; set; }
        public string? MARKET_CODE { get; set; }
        public string? SOURCE_CODE { get; set; }
        public string? BACK_TO_BACK_YN { get; set; }
        public DateTime? BEGIN_BOOKING_DATE { get; set; }
        public DateTime? END_BOOKING_DATE { get; set; }
        public string? YIELDABLE_YN { get; set; }
        public string? HIGHLIGHT_RATE_AMOUNT_YN { get; set; }
        public string? SHOW_RATE_AMOUNT_YN { get; set; }
        public string? DAYUSE_YN { get; set; }
        public string? PRINT_RATE_YN { get; set; }
        public string? TRX_CODE { get; set; }
        public string? TRX_CODE_WK { get; set; }
        public string? PKG_TRX_CODE { get; set; }
        public string? TRX_TAX_INCL_YN { get; set; }
        public string? PKG_TRX_CODE_WK { get; set; }
        public string? PROFIT_TRX_CODE { get; set; }
        public string? TRX_WK_TAX_INCL_YN { get; set; }
        public string? PKG_TRX_TAX_INCL_YN { get; set; }
        public string? PKG_TRX_WK_TAX_INCL_YN { get; set; }
        public string? CURRENCY_CODE { get; set; }
        public string? EXCHANGE_POSTING_TYPE { get; set; }
        public string? NEGOTIATED { get; set; }
        public string? COMPLIMENTARY_YN { get; set; }
        public string? HOUSE_USE_YN { get; set; }
        public DateTime? INACTIVE_DATE { get; set; }
        public string? POSTING_RHYTHM { get; set; }
        public string? WEEKEND_DAYS { get; set; }
        public string? RATE_CALENDAR_YN { get; set; }
        public string? ADVANCE_BOOKING { get; set; }
        public string? CLOSED_TO_ARRIVAL { get; set; }
        public string? FREQUENT_FLYER_YN { get; set; }
        public string? MAX_LOS { get; set; }
        public string? ADDITION { get; set; }
        public string? MULTIPLICATION { get; set; }
        public string? SHORT_INFO { get; set; }
        public string? LONG_INFO { get; set; }
        public string? RATE_CODE_LOCKED { get; set; }
        public string? INSERT_USER { get; set; }
        public DateTime? INSERT_DATE { get; set; }
        public string? UPDATE_USER { get; set; }
        public DateTime? UPDATE_DATE { get; set; }
        public string? RATE_BUCKET { get; set; }
        public string? EXTERNAL_LOCKED { get; set; }
        public string? YIELD_AS { get; set; }
        public string? GDS_ALLOWED_YN { get; set; }
        public string? LOYALTY_PROGRAM_YN { get; set; }
        public string? REDEMPTION_RATE_YN { get; set; }
        public string? DISPLAY_SET { get; set; }
        public string? BASE_FLT_PCT { get; set; }
        public string? BASE_ROUNDING { get; set; }
        public string? BASE_AMOUNT { get; set; }
        public string? DISTRIBUTE_YN { get; set; }
        public string? TIERED_YN { get; set; }
        public string? DEPT_CODE { get; set; }
        public string? WK_DEPT_CODE { get; set; }
        public string? COMMISSION_PCT { get; set; }
        public string? DISCOUNT_YN { get; set; }
        public string? GROUP_CODE { get; set; }
        public string? RATE_LEVEL { get; set; }
        public string? ROD_YN { get; set; }
        public string? ROD_BASED_YN { get; set; }
        public string? ROD_BASE_FLT_PCT { get; set; }
        public string? ROD_BASE_ROUNDING { get; set; }
        public string? ROD_BASE_AMOUNT { get; set; }
        public string? RATEINFO_URL { get; set; }
        public string? COMMISSIONABLE_YN { get; set; }
        public string? FIT_DISCOUNT_PERC { get; set; }
        public string? BFST_INCL_YN { get; set; }
        public string? BFST_PRICE { get; set; }
        public string? SERVICE_INCL_YN { get; set; }
        public string? FIT_DISCOUNT_LEVEL { get; set; }
        public string? SERVICE_PERC { get; set; }
        public string? COMMISSIONABLE_PERC { get; set; }
        public string? DBL_RM_SUPPLEMENT_YN { get; set; }
        public string? DBL_RM_SUPPLEMENT_PRICE { get; set; }
        public string? TAX_INCLUDED_YN { get; set; }
        public string? TAX_INCLUDED_PERC { get; set; }
        public string? DAILY_RATES_YN { get; set; }
        public string? MAX_ADVANCE_BOOKING { get; set; }
        public string? BBAR_YN { get; set; }
        public string? BBAR_BASED_YN { get; set; }
        public string? BBAR_BASE_FLT_PCT { get; set; }
        public string? BBAR_BASE_ROUNDING { get; set; }
        public string? BBAR_BASE_AMOUNT { get; set; }
        public string? YM_CODE { get; set; }
        public string? MIN_OCCUPANCY { get; set; }
        public string? MAX_OCCUPANCY { get; set; }
        public string? AVAILABILITY_UPDATE_YN { get; set; }
        public string? RATES_TO_GDS_YN { get; set; }
        public string? DISPLAY_REGIONAL_YN { get; set; }
        public string? MFN_UPLOAD_YN { get; set; }
        public string? CHANGE_STATE { get; set; }
        public DateTime? SDOW_BEGIN_BOOKING_DATE { get; set; }
        public DateTime? SDOW_END_BOOKING_DATE { get; set; }
        public string? DBASE_RATE_CODE { get; set; }
        public string? DBASE_FLT_PCT { get; set; }
        public string? DBASE_ROUNDING { get; set; }
        public string? DBASE_AMOUNT { get; set; }
        public string? DBASE_COMPARE_YN { get; set; }
        public string? RATE_FLOOR { get; set; }
        public string? ASB_RATE_CYCLE { get; set; }
        public string? ADV_BASE_RATE_CODE { get; set; }
        public string? ADV_BASE_ROUNDING { get; set; }
        public string? PENDING_APPROVAL_YN { get; set; }
        public string? UPSELL_YN { get; set; }
        public string? OWNER_RATE_YN { get; set; }
        public string? MANDATE_RESV_PROFILES { get; set; }
        public string? BBAR_COMPARE_YN { get; set; }
        public string? BYPASS_HURDLE_YN { get; set; }
        public string? ORS_SELL_SEQUENCE { get; set; }
        public string? ADV_BASE_COMPARE_YN { get; set; }
        public string? BYPASS_RANK_CHECK_YN { get; set; }
        public string? RANK_VALUE { get; set; }
        public string? RANK_ADJUSTMENT_FACTOR { get; set; }
        public string? DEFAULT_TO_HIGHEST_BAR_YN { get; set; }
        public string? RATE_FLOOR_OVERRIDE_YN { get; set; }
        public string? EXTRA_PERSON_CHARGE_BEGINS { get; set; }
        public string? CURR_CODE_DECIMAL_POS { get; set; }
        public string? OCCUPANCY_LEVEL { get; set; }
        public string? OVERRIDE_PACKAGE_YN { get; set; }
        public string? CAT_PKG_YN { get; set; }
        public string? CAT_PKG_CODE { get; set; }
        public string? REPEAT_POSTING_RHYTHM_YN { get; set; }
        public string? DISCOUNT_RATE_AMOUNT { get; set; }
        public string? DISCOUNT_RATE_PERCENTAGE_YN { get; set; }
        public string? POSTING_RHYTHM_NIGHTS { get; set; }
        public string? ADV_DAILY_RATE_YN { get; set; }
        public string? ADV_DAILY_BASE_YN { get; set; }
        public string? VOUCHER_BENEFIT_RATE_YN { get; set; }
        public string? BASE_TYPE { get; set; }
        public string? PRIVILEGED_YN { get; set; }
        public string? PRIVILEGED_RESTRICTION_YN { get; set; }
        public string? DEPOSIT_MATURITY_PREFERENCE { get; set; }
        public string? MOBILE_CHKOUT_ALLOWED { get; set; }
        public string? ROOM_ASSIGNMENT_VALUE { get; set; }
        public string? MARSHA_RATE_PROGRAM { get; set; }
        public string? MOBILE_CHECKIN_ALLOWED_YN { get; set; }
        public string? OCCUPANCY_BASED_YN { get; set; }
        public DateTime? RNA_INSERTDATE { get; set; } = null;
        public DateTime? RNA_UPDATEDATE { get; set; } = null;
        public string? DELETED_FLAG { get; set; } = "";
    }
}
