using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WorkerOperaCloud.Models
{
    public class Mdl_Resort
    {
        public string? RESORT { get; set; } = "";
        public DateTime? BEGIN_DATE { get; set; }
        public string? NAME { get; set; } = "";
        public string? LEGAL_OWNER { get; set; } = "";
        public string? COUNTRY_CODE { get; set; } = "";
        public string? CRS_RESORT { get; set; } = "";
        public string? STREET { get; set; } = "";
        public string? POST_CODE { get; set; } = "";
        public string? CITY { get; set; } = "";
        public string? STATE { get; set; } = "";
        public string? TELEPHONE { get; set; } = "";
        public string? FAX { get; set; } = "";
        public string? WEBADDRESS { get; set; } = "";
        public string? TOLLFREE { get; set; } = "";
        public string? EMAIL { get; set; } = "";
        public string? KEEP_AVAILABILITY { get; set; } = "";
        public string? BUDGET_MONTH { get; set; } = "";
        public string? SAVE_PROFILES { get; set; } = "";
        public string? DEFAULT_RESERVATION_TYPE { get; set; } = "";
        public string? BLOCK { get; set; } = "";
        public string? CURRENCY_SYMBOL { get; set; } = "";
        public string? SOURCE_COMMISSION { get; set; } = "";
        public string? TA_COMMISSION { get; set; } = "";
        public DateTime? CHECK_IN_TIME { get; set; }
        public DateTime? CHECK_OUT_TIME { get; set; }
        public string? LONG_STAY_CONTROL { get; set; } = "";
        public string? CREDIT_LIMIT { get; set; } = "";
        public string? NUMBER_ROOMS { get; set; } = "";
        public string? NUMBER_FLOORS { get; set; } = "";
        public string? NUMBER_BEDS { get; set; } = "";
        public string? RHYTHM_SHEETS { get; set; } = "";
        public string? RHYTHM_TOWELS { get; set; } = "";
        public string? BASE_LANGUAGE { get; set; } = "";
        public string? FOLIO_LANGUAGE1 { get; set; } = "";
        public string? FOLIO_LANGUAGE2 { get; set; } = "";
        public string? FOLIO_LANGUAGE3 { get; set; } = "";
        public string? FOLIO_LANGUAGE4 { get; set; } = "";
        public string? WARNING_AMOUNT { get; set; } = "";
        public string? THOUSAND_SEPARATOR { get; set; } = "";
        public string? PACKAGE_PROFIT { get; set; } = "";
        public string? PACKAGE_LOSS { get; set; } = "";
        public string? DECIMAL_PLACES { get; set; } = "";
        public string? DECIMAL_SEPARATOR { get; set; } = "";
        public string? SHORT_DATE_FORMAT { get; set; } = "";
        public string? LONG_DATE_FORMAT { get; set; } = "";
        public string? DATE_SEPARATOR { get; set; } = "";
        public string? FONT { get; set; } = "";
        public string? COPIES { get; set; } = "";
        public string? DEFAULT_FOLIO_STYLE { get; set; } = "";
        public string? INDIVIDUAL_ROOM_WARNING { get; set; } = "";
        public string? GROUP_ROOM_WARNING { get; set; } = "";
        public DateTime? VIDEO_CO_START { get; set; }
        public DateTime? VIDEO_CO_STOP { get; set; }
        public string? PASSERBY_SOURCE { get; set; } = "";
        public string? PASSERBY_MARKET { get; set; } = "";
        public string? AR_COMPANY { get; set; } = "";
        public string? AR_AGENT { get; set; } = "";
        public string? AR_GROUPS { get; set; } = "";
        public string? AR_INDIVIDUALS { get; set; } = "";
        public string? AR_ACCT_NO_MAND_YN { get; set; } = "";
        public string? AGING_LEVEL1 { get; set; } = "";
        public string? AGING_LEVEL2 { get; set; } = "";
        public string? AGING_LEVEL3 { get; set; } = "";
        public string? AGING_LEVEL4 { get; set; } = "";
        public string? AGING_LEVEL5 { get; set; } = "";
        public string? AR_ACCT_NO_FORMAT { get; set; } = "";
        public string? DATE_FOR_AGING { get; set; } = "";
        public string? ZERO_INV_PUR_DAYS { get; set; } = "";
        public string? MIN_DAYS_BET_2_REMINDER_LETTER { get; set; } = "";
        public string? ALLOWANCE_PERIOD_ADJ { get; set; } = "";
        public string? HOTEL_ID { get; set; } = "";
        public DateTime? INSERT_DATE { get; set; }
        public string? INSERT_USER { get; set; } = "";
        public DateTime? UPDATE_DATE { get; set; }
        public string? UPDATE_USER { get; set; } = "";
        public string? CURRENCY_CODE { get; set; } = "";
        public string? CURRENCY_DECIMALS { get; set; } = "";
        public string? EXCHANGE_POSTING_TYPE { get; set; } = "";
        public string? TURNAWAY_CODE { get; set; } = "";
        public string? SUMM_CURRENCY_CODE { get; set; } = "";
        public string? FAX_NO_FORMAT { get; set; } = "";
        public string? TELEPHONE_NO_FORMAT { get; set; } = "";
        public string? LOCAL_CURRENCY_FORMAT { get; set; } = "";
        public string? DEFAULT_PROPERTY_ADDRESS { get; set; } = "";
        public string? DEFAULT_GUEST_ADDRESS { get; set; } = "";
        public string? LICENSE_CODE { get; set; } = "";
        public DateTime? EXPIRY_DATE { get; set; }
        public string? TIME_FORMAT { get; set; } = "";
        public string? NAME_ID_LINK { get; set; } = "";
        public string? DUTY_MANAGER_PAGER { get; set; } = "";
        public string? CHAIN_CODE { get; set; } = "";
        public string? RESORT_TYPE { get; set; } = "";
        public DateTime? END_DATE { get; set; }
        public string? GENMGR { get; set; } = "";
        public string? DIRSALES { get; set; } = "";
        public string? LEADSEND { get; set; } = "";
        public string? AIRPORT { get; set; } = "";
        public string? AIRPORT_DISTANCE { get; set; } = "";
        public string? AIRPORT_TIME { get; set; } = "";
        public string? HOTEL_TYPE { get; set; } = "";
        public string? OWNERSHIP { get; set; } = "";
        public string? QUOTED_CURRENCY { get; set; } = "";
        public string? COM_METHOD { get; set; } = "";
        public string? COM_ADDRESS { get; set; } = "";
        public string? INVENTORY_YN { get; set; } = "";
        public string? NOTES { get; set; } = "";
        public string? SGL_NUM { get; set; } = "";
        public string? SGL_RATE1 { get; set; } = "";
        public string? SGL_RATE2 { get; set; } = "";
        public string? DBL_NUM { get; set; } = "";
        public string? DBL_RATE1 { get; set; } = "";
        public string? DBL_RATE2 { get; set; } = "";
        public string? TPL_NUM { get; set; } = "";
        public string? TPL_RATE1 { get; set; } = "";
        public string? TPL_RATE2 { get; set; } = "";
        public string? SUI_NUM { get; set; } = "";
        public string? SUI_RATE1 { get; set; } = "";
        public string? SUI_RATE2 { get; set; } = "";
        public string? TOT_ROOMS { get; set; } = "";
        public string? SEASON1 { get; set; } = "";
        public string? SEASON2 { get; set; } = "";
        public string? SEASON3 { get; set; } = "";
        public string? SEASON4 { get; set; } = "";
        public string? SEASON5 { get; set; } = "";
        public string? HOTEL_FC { get; set; } = "";
        public string? MEETING_FC { get; set; } = "";
        public string? BR_AREA { get; set; } = "";
        public string? BR_SEATS { get; set; } = "";
        public string? MEET_SPACE { get; set; } = "";
        public string? MEET_ROOMS { get; set; } = "";
        public string? MEET_SEATS { get; set; } = "";
        public string? RESTAURANT { get; set; } = "";
        public string? IMG_HOTEL_ID { get; set; } = "";
        public string? IMG_DIRECTION_ID { get; set; } = "";
        public string? IMG_MAP_ID { get; set; } = "";
        public string? ALLOW_LOGIN_YN { get; set; } = "";
        public string? AR_BAL_TRX_CODE { get; set; } = "";
        public string? AR_CREDIT_TRX_CODE { get; set; } = "";
        public string? AR_TYPEWRITER { get; set; } = "";
        public string? AR_SETTLE_CODE { get; set; } = "";
        public string? CASH_SHIFT_DROP { get; set; } = "";
        public string? CHECK_EXG_PAIDOUT { get; set; } = "";
        public string? CHECK_SHIFT_DROP { get; set; } = "";
        public string? CHECK_TRXCODE { get; set; } = "";
        public string? CURRENCY_EXG_PAIDOUT { get; set; } = "";
        public string? DEPOSIT_LED_TRX_CODE { get; set; } = "";
        public DateTime? FISCAL_START_DATE { get; set; }
        public DateTime? FISCAL_END_DATE { get; set; }
        public string? FISCAL_PERIOD_TYPE { get; set; } = "";
        public string? DEFAULT_COMMISSION_PERCENTAGE { get; set; } = "";
        public string? DEFAULT_PREPAID_COMM { get; set; } = "";
        public string? DEFAULT_TRX_COMM_CODE { get; set; } = "";
        public string? FILE_TRANSFER_FORMAT { get; set; } = "";
        public string? CONFIGURATION_MODE { get; set; } = "";
        public string? CONFIRM_REGCARD_PRINTER { get; set; } = "";
        public string? DEFAULT_PRINTER { get; set; } = "";
        public string? DEFAULT_REGISTRATION_CARD { get; set; } = "";
        public string? WEEKEND_DAYS { get; set; } = "";
        public string? DEFAULT_GROUPS_RATE_CODE { get; set; } = "";
        public string? MAX_NO_NIGHTS { get; set; } = "";
        public string? AWARDS_TIMEOUT { get; set; } = "";
        public string? DEFAULT_POSTING_ROOM { get; set; } = "";
        public string? GUEST_LOOKUP_TIMEOUT { get; set; } = "";
        public string? VIDEOCHECKOUT_PRINTER { get; set; } = "";
        public string? WAKE_UP_DELAY { get; set; } = "";
        public string? NIGHT_AUDIT_CASHIER_ID { get; set; } = "";
        public string? COMPANY_ADDRESS_TYPE { get; set; } = "";
        public string? COMPANY_PHONE_TYPE { get; set; } = "";
        public string? DEFAULT_FAX_TYPE { get; set; } = "";
        public string? DEFAULT_MEMBERSHIP_TYPE { get; set; } = "";
        public string? INDIVIDUAL_ADDRESS_TYPE { get; set; } = "";
        public string? INDIVIDUAL_PHONE_TYPE { get; set; } = "";
        public string? DFLT_PKG_TRAN_CODE { get; set; } = "";
        public string? DFLT_TRAN_CODE_RATE_CODE { get; set; } = "";
        public string? MAX_OCCUPANCY { get; set; } = "";
        public string? INACTIVE_DAYS_FOR_GUEST_PROFIL { get; set; } = "";
        public string? DEFAULT_RATE_CODE { get; set; } = "";
        public string? PER_RESERVATION_ROOM_LIMIT { get; set; } = "";
        public string? SCRIPT_ID { get; set; } = "";
        public string? CRO_CODE { get; set; } = "";
        public string? FLOW_CODE { get; set; } = "";
        public string? EXT_PROPERTY_CODE { get; set; } = "";
        public string? EXT_EXP_FILE_LOCATION { get; set; } = "";
        public string? REGION_CODE { get; set; } = "";
        public string? OPUS_CURRENCY_CODE { get; set; } = "";
        public string? COM_NAME_XREF_ID { get; set; } = "";
        public string? HOTEL_CODE { get; set; } = "";
        public string? CURTAIN_COLOR { get; set; } = "";
        public DateTime? RECONCILE_DATE { get; set; }
        public DateTime? PAYMENT_DATE { get; set; }
        public string? PATH_ID { get; set; } = "";
        public string? XRESORT_NUMBER { get; set; } = "";
        public string? DIRECTIONS { get; set; } = "";
        public string? DESTINATION_ID { get; set; } = "";
        public string? MAX_CREDIT_DAYS { get; set; } = "";
        public string? PATH { get; set; } = "";
        public string? ACCESS_CODE { get; set; } = "";
        public string? FLAGS { get; set; } = "";
        public string? TOURIST_NUMBER { get; set; } = "";
        public string? DISABLE_LOGIN_YN { get; set; } = "";
        public string? INT_TAX_INCLUDED_YN { get; set; } = "";
        public string? DOWNLOAD_REST_YN { get; set; } = "";
        public string? TIMEZONE_REGION { get; set; } = "";
        public string? PROPINFO_URL { get; set; } = "";
        public string? LATITUDE { get; set; } = "";
        public string? LONGITUDE { get; set; } = "";
        public string? TRANSLATE_MULTICHAR_YN { get; set; } = "";
        public string? PROP_PIC_URL { get; set; } = "";
        public string? PROP_MAP_URL { get; set; } = "";
        public string? CATERING_CURRENCY_CODE { get; set; } = "";
        public string? CATERING_CURRENCY_FORMAT { get; set; } = "";
        public string? QTY_SINGLE_ROOMS { get; set; } = "";
        public string? QTY_DOUBLE_ROOMS { get; set; } = "";
        public string? QTY_TWIN_ROOMS { get; set; } = "";
        public string? QTY_SUITES { get; set; } = "";
        public string? QTY_GUEST_ROOM_FLOORS { get; set; } = "";
        public string? QTY_GUEST_ELEVATORS { get; set; } = "";
        public string? QTY_NON_SMOKING_ROOMS { get; set; } = "";
        public string? QTY_CONNECTING_ROOMS { get; set; } = "";
        public string? QTY_HANDICAPPED_ROOMS { get; set; } = "";
        public string? QTY_FAMILY_ROOMS { get; set; } = "";
        public string? MAX_ADULTS_FAMILY_ROOM { get; set; } = "";
        public string? MAX_CHILDREN_FAMILY_ROOM { get; set; } = "";
        public string? FLOOR_NUM_EXECUTIVE_FLOOR { get; set; } = "";
        public string? ROOM_AMENITY { get; set; } = "";
        public string? SHOP_DESCRIPTION { get; set; } = "";
        public string? DEFAULT_RATECODE_RACK { get; set; } = "";
        public string? DEFAULT_RATECODE_PCR { get; set; } = "";
        public string? BLACKOUT_PERIOD_NOTES { get; set; } = "";
        public string? EXTERNAL_SC_YN { get; set; } = "";
        public string? SEND_LEAD_AS_BOOKING_YN { get; set; } = "";
        public string? EXP_HOTEL_CODE { get; set; } = "";
        public string? LIC_ROOM_INFO { get; set; } = "";
        public string? FNS_TIER { get; set; } = "";
        public string? BRAND_CODE { get; set; } = "";
        public string? MBS_SUPPORTED_YN { get; set; } = "";
        public string? VAT_ID { get; set; } = "";
        public DateTime? RNA_INSERTDATE { get; set; } = null;
        public DateTime? RNA_UPDATEDATE { get; set; } = null;
        public string? DELETED_FLAG { get; set; } = "";
    }
}
